# Redefine theme overrides for this site.

info:
  title: Hexo
  subtitle: ''
  author: John Doe
  url: http://example.com

home_banner:
  title: Hexo
  subtitle:
    text:
      - 欢迎来到本站

comment:
  config:
    giscus:
      lang: zh-CN

footer:
  start: 2026/05/26 01:00:00
