# Redefine theme overrides for this site.

info:
  title: 三相共存点
  subtitle: 'Identity'
  author: Haskina
  url: https://idsmile.top/

defaults:
  avatar: /image/avatar.webp

global:
  website_counter:
    url: https://cn.vercount.one/js
    enable: true
    site_pv: true
    site_uv: true
    post_pv: true

home_banner:
  title: 但在此山中，云深不知处
  subtitle:
    text:
      - 欢迎来到本站

navbar:
  links:
    Home:
      path: /
      icon: fa-regular fa-house
    归档:
      path: /archives/
      icon: fa-regular fa-archive
    碎碎念:
      path: /shuoshuo/
      icon: fa-regular fa-comment-dots
    留言板:
      path: /comments/
      icon: fa-regular fa-message
    友链:
      path: /friends/
      icon: fa-regular fa-link
    关于:
      path: /about/
      icon: fa-regular fa-user

comment:
  config:
    giscus:
      lang: zh-CN

footer:
  start: 2026/05/26 01:00:00

page_templates:
  friends_column: 3
